Change port detail page title to include "MacOS"
macports/macports-webapp pull request #260
Opened 2021-02-05 13:23 UTC by gagarine

The page do not mention MacOS. This could improve SEO a bit.

2021-02-05 13:26 UTC, gagarine commented
In adition I believe it should contain the install command, but I didn't find a nice way to add it in the current design.

![Screenshot 2021-02-05 at 14 24 43](https://user-images.githubusercontent.com/164074/107039296-ff061280-67bd-11eb-82f1-5821dea52bf5.png)

It should also have clear and big link back to main macport website. Today if someone arrive on a port details without knowing what is macport, he will certainly be lost.

2021-02-07 13:53 UTC, neverpanic requested changes

2021-02-07 13:53 UTC, neverpanic commented on app/ports/templates/ports/portdetail.html
> +{% block title %}Install {{ req_port.name }} Port on MacOS -  |{% endblock %}
```suggestion
{% block title %}Install {{ req_port.name }} Port on macOS -  |{% endblock %}
```
Apple's official capitalization of "macOS" starts with a lower case "m". Other than that, this lg2m.

2021-02-07 16:04 UTC, gagarine commented
The build seem to fail. But it seem to be a problem out of this commit.

2021-02-08 18:54 UTC, neverpanic approved these changes
Change lg2m, let me look at the build failure, though – this won't get deployed if the build fails.

2021-02-09 19:52 UTC, neverpanic commented
Seems like this needs updated python dependencies. Let me check what I can do about those.

2021-02-09 20:45 UTC, neverpanic commented
See also #261. CI also needs fixing, maybe I'll find time to take a look at this later or in the coming days.

2021-02-09 22:27 UTC, merged

2021-02-09 22:41 UTC, neverpanic commented
So now the title tag is `Install htop Port on macOS - | MacPorts`. That's not really ideal.

Shouldn't it rather be something like `Install htop on macOS | MacPorts`?

2021-02-10 12:08 UTC, gagarine commented
> Shouldn't it rather be something like Install htop on macOS | MacPorts?

Yes. It would be cool. I didn’t propose this because I taught you may want to keep that it is a port.  But with MacPorts as the seconde part of the url I think it’s ok. 

What about `Install htop on macOS | MacPorts Package Manager` ?

 In addition adding the install commande would be great so people can copy and past and new user can see how easy it is.

2021-02-10 17:29 UTC, neverpanic commented
I think people google "install xyz macOS", not necessarily "install xyz macOS package manager", so I don't think we need the "package manager" addition. It would be great if we could drop the dash before the pipe, though, that looks really out of place.